import db from ".";

import { popularSearchTable } from "./schema/popsearch";

export const seedData = [
  // Beer
  { brandName: "Kingfisher", category: "Beer" },
  { brandName: "Haywards 5000", category: "Beer" },
  { brandName: "Knock Out", category: "Beer" },
  { brandName: "Kalyani Black Label", category: "Beer" },
  { brandName: "Sandpiper", category: "Beer" },
  { brandName: "Bullet Super Strong", category: "Beer" },
  { brandName: "White Owl", category: "Beer" },
  { brandName: "Zingaro", category: "Beer" },
  { brandName: "London Pilsner", category: "Beer" },
  { brandName: "Foster's", category: "Beer" },
  { brandName: "Royal Challenge Premium Lager", category: "Beer" },
  { brandName: "Medusa", category: "Beer" },
  { brandName: "Woodpecker", category: "Beer" },
  { brandName: "Bira 91", category: "Beer" },
  { brandName: "Simba", category: "Beer" },
  { brandName: "Bee Young", category: "Beer" },
  { brandName: "Godfather", category: "Beer" },
  { brandName: "Corona", category: "Beer" },
  { brandName: "Tuborg", category: "Beer" },
  { brandName: "Budweiser", category: "Beer" },
  { brandName: "Cobra", category: "Beer" },
  { brandName: "Singha", category: "Beer" },
  { brandName: "Tsingtao", category: "Beer" },
  { brandName: "Heineken", category: "Beer" },
  { brandName: "Carlsberg", category: "Beer" },

  // Wine
  { brandName: "Sula Vineyards", category: "Wine" },
  { brandName: "Grover Zampa", category: "Wine" },
  { brandName: "Fratelli Wines", category: "Wine" },
  { brandName: "Big Banyan", category: "Wine" },
  { brandName: "York Winery", category: "Wine" },
  { brandName: "KRSMA", category: "Wine" },
  { brandName: "Vallonne", category: "Wine" },
  { brandName: "Rhythm Wines", category: "Wine" },
  { brandName: "Four Seasons", category: "Wine" },
  { brandName: "Myra Vineyards", category: "Wine" },
  { brandName: "Chateau d'Ori", category: "Wine" },
  { brandName: "Nine Hills", category: "Wine" },
  { brandName: "Chandon India", category: "Wine" },
  { brandName: "Jacob's Creek", category: "Wine" },
  { brandName: "Yellow Tail", category: "Wine" },
  { brandName: "Hardys", category: "Wine" },
  { brandName: "Barefoot", category: "Wine" },
  { brandName: "Casillero del Diablo", category: "Wine" },
  { brandName: "Penfolds", category: "Wine" },
  { brandName: "Concha y Toro", category: "Wine" },
  { brandName: "Santa Rita", category: "Wine" },
  { brandName: "Blossom Hill", category: "Wine" },

  // Whiskey
  { brandName: "McDowell's No.1", category: "Whiskey" },
  { brandName: "Royal Stag", category: "Whiskey" },
  { brandName: "Imperial Blue", category: "Whiskey" },
  { brandName: "Officer's Choice", category: "Whiskey" },
  { brandName: "Blenders Pride", category: "Whiskey" },
  { brandName: "8PM Whisky", category: "Whiskey" },
  { brandName: "Royal Challenge", category: "Whiskey" },
  { brandName: "Old Admiral", category: "Whiskey" },
  { brandName: "Peter Scot", category: "Whiskey" },
  { brandName: "Red Knight", category: "Whiskey" },
  { brandName: "Rowson's Reserve", category: "Whiskey" },
  { brandName: "Signature", category: "Whiskey" },
  { brandName: "Amrut", category: "Whiskey" },
  { brandName: "Paul John", category: "Whiskey" },
  { brandName: "Rampur", category: "Whiskey" },
  { brandName: "Johnnie Walker", category: "Whiskey" },
  { brandName: "Jack Daniel's", category: "Whiskey" },
  { brandName: "Jim Beam", category: "Whiskey" },
  { brandName: "Jameson", category: "Whiskey" },
  { brandName: "Chivas Regal", category: "Whiskey" },
  { brandName: "Ballantine's", category: "Whiskey" },
  { brandName: "Glenfiddich", category: "Whiskey" },
  { brandName: "Glenlivet", category: "Whiskey" },
  { brandName: "Teachers", category: "Whiskey" },
  { brandName: "Dewar's", category: "Whiskey" },
  { brandName: "Grant's", category: "Whiskey" },
  { brandName: "100 Pipers", category: "Whiskey" },
  { brandName: "Black Dog", category: "Whiskey" },
  { brandName: "Legacy", category: "Whiskey" },
  { brandName: "Antiquity", category: "Whiskey" },
  { brandName: "Black & White", category: "Whiskey" },
  { brandName: "Royal Salute", category: "Whiskey" },

  // Vodka
  { brandName: "Magic Moments", category: "Vodka" },
  { brandName: "Romanov", category: "Vodka" },
  { brandName: "White Mischief", category: "Vodka" },
  { brandName: "8PM Vodka", category: "Vodka" },
  { brandName: "9XO Vodka", category: "Vodka" },
  { brandName: "Smirnoff", category: "Vodka" },
  { brandName: "Absolut", category: "Vodka" },
  { brandName: "Belvedere", category: "Vodka" },
  { brandName: "Grey Goose", category: "Vodka" },
  { brandName: "Russian Standard", category: "Vodka" },
  { brandName: "Stolichnaya", category: "Vodka" },
  { brandName: "Svedka", category: "Vodka" },
  { brandName: "Ketel One", category: "Vodka" },
  { brandName: "Tito's", category: "Vodka" },
  { brandName: "SKYY Vodka", category: "Vodka" },

  // Rum
  { brandName: "Old Monk", category: "Rum" },
  { brandName: "McDowell's No.1 Celebration Rum", category: "Rum" },
  { brandName: "Bacardi", category: "Rum" },
  { brandName: "Captain Morgan", category: "Rum" },
  { brandName: "Amrut Two Indies", category: "Rum" },
  { brandName: "Segredo Aldeia", category: "Rum" },
  { brandName: "Makazai", category: "Rum" },
  { brandName: "Ron Diplomático", category: "Rum" },
  { brandName: "Havana Club", category: "Rum" },
  { brandName: "Camino Real", category: "Rum" },
  { brandName: "Plantation Rum", category: "Rum" },
  { brandName: "Holika", category: "Rum" },
  { brandName: "Mount Gay", category: "Rum" },
  { brandName: "Myers's Rum", category: "Rum" },

  // Gin
  { brandName: "Bombay Sapphire", category: "Gin" },
  { brandName: "Tanqueray", category: "Gin" },
  { brandName: "Beefeater", category: "Gin" },
  { brandName: "Gordon's", category: "Gin" },
  { brandName: "Hendrick's", category: "Gin" },
  { brandName: "Stranger & Sons", category: "Gin" },
  { brandName: "Greater Than", category: "Gin" },
  { brandName: "Hapusa", category: "Gin" },
  { brandName: "Jaisalmer Gin", category: "Gin" },
  { brandName: "Metta Gin", category: "Gin" },
  { brandName: "Kamala Gin", category: "Gin" },
  { brandName: "Riversmith Gin", category: "Gin" },

  // Tequila
  { brandName: "Jose Cuervo", category: "Tequila" },
  { brandName: "Don Julio", category: "Tequila" },
  { brandName: "Patrón", category: "Tequila" },
  { brandName: "1800 Tequila", category: "Tequila" },
  { brandName: "El Jimador", category: "Tequila" },
  { brandName: "Sauza", category: "Tequila" },
  { brandName: "Olmeca", category: "Tequila" },
  { brandName: "Camino Real", category: "Tequila" },
  { brandName: "DesmondJi", category: "Tequila" },
  { brandName: "Don Pilar", category: "Tequila" },
  { brandName: "Dos Lunas", category: "Tequila" },

  // Brandy
  { brandName: "Old Admiral", category: "Brandy" },
  { brandName: "Honey Bee", category: "Brandy" },
  { brandName: "Mansion House", category: "Brandy" },
  { brandName: "Morpheus XO", category: "Brandy" },
  { brandName: "Dreher", category: "Brandy" },
  { brandName: "Hennessy", category: "Brandy" },
  { brandName: "Remy Martin", category: "Brandy" },
  { brandName: "Martell", category: "Brandy" },
  { brandName: "Courvoisier", category: "Brandy" },
  { brandName: "Camus", category: "Brandy" },
  { brandName: "McDowell's VSOP", category: "Brandy" },
  { brandName: "Emperador", category: "Brandy" },

  // Cocktails (RTD / pre-mixed)
  { brandName: "Bacardi Breezer", category: "Cocktails" },
  { brandName: "Smirnoff Ice", category: "Cocktails" },
  { brandName: "Magic Moments Vodka Spritz", category: "Cocktails" },
  { brandName: "Old Monk Rum & Cola", category: "Cocktails" },
  { brandName: "Ritaq Margarita", category: "Cocktails" },
  { brandName: "Maaza Vodka Cocktails", category: "Cocktails" },
  { brandName: "Wai Wai Frozen Daiquiris", category: "Cocktails" },
  { brandName: "Cobra Beer Drinks", category: "Cocktails" },
  { brandName: "Bira 91 Ready To Drink", category: "Cocktails" },

  // Champagne / Sparkling
  { brandName: "Moet & Chandon", category: "Champagne" },
  { brandName: "Veuve Clicquot", category: "Champagne" },
  { brandName: "Dom Perignon", category: "Champagne" },
  { brandName: "Krug", category: "Champagne" },
  { brandName: "Laurent-Perrier", category: "Champagne" },
  { brandName: "Bollinger", category: "Champagne" },
  { brandName: "Piper-Heidsieck", category: "Champagne" },
  { brandName: "Louis Roederer (Cristal)", category: "Champagne" },
  { brandName: "GH Mumm", category: "Champagne" },
  { brandName: "Perrier-Jouet", category: "Champagne" },
  { brandName: "Nicolas Feuillatte", category: "Champagne" },
  { brandName: "Taittinger", category: "Champagne" },
  { brandName: "Ruinart", category: "Champagne" },
  { brandName: "Pommery", category: "Champagne" },
  { brandName: "Canard-Duchene", category: "Champagne" },
  { brandName: "Alfred Gratien", category: "Champagne" },
  { brandName: "Gosset", category: "Champagne" },
  { brandName: "Pol Roger", category: "Champagne" },
];

export async function seedPopularSearches() {
  await db
    .insert(popularSearchTable)
    .values(seedData)
    .onConflictDoNothing()
    .then(() => {
      console.log("brandNames seeded");
    });
}

seedPopularSearches();
